services:
  - type: web
    name: aust-cp-standings-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
